vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: ge0/0
        ip:
          address: 10.64.100.45/16
        tunnel_interface:
        shutdown: false
        allow_service:
          - all
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 10.64.100.1
