all:
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_network_os: ios
    netconf_template_os: ios
  children:
    routers:
      hosts:
        iosv-1:
        iosv-2:
        iosv-3:
    clients:
      hosts:
        host_site3:
        host_site4:
        host_site5:
    viptela:
      vars:
        netconf_template_os: viptela
      children:
        viptela_control:
          children:
            vmanage_hosts:
              hosts:
                vManage_1:
            vbond_hosts:
              hosts:
                vBond:
            vsmart_hosts:
              hosts:
                vSmart_100:
                vSmart_101:        
        viptela_vedge:
          hosts:
            vEdge_1:
            vEdge_2:
            vEdge_3:
            vEdge_4:
            vEdge_5:
            vEdge_6:
            vEdge_7:
            vEdge_8:

