organization_name: "lonlab-sdwan"
vbond:
  remote: 10.64.100.45
serial_number_file: "{{ playbook_dir }}/licenses/viptela_serial_file.viptela"
viptela_cert_dir: "{{ lookup('env', 'PWD') }}/myCA"
# Encrypt/Vault this in real life
viptela_CA_passphrase: Cisc0123
