vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: ge0/0
        ip:
          address: 10.65.11.1/16
        tunnel_interface:
        shutdown: false
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 10.65.100.1
  - vpn_id: 1
    interfaces:
      - if_name: ge0/2
        ip:
          address: 10.1.111.1/24
        shutdown: false
