vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: eth1 
        ip:
          address: 10.64.100.42/16
        tunnel_interface:
        shutdown: false
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 10.64.100.1
