vpn_instances:
  - vpn_id: 0
    interfaces:
      - if_name: eth1
        ip:
          address: 10.64.100.80/16
        tunnel_interface: true
        allow_service:
        - all
        shutdown: false
    routes:
      - prefix: 0.0.0.0/0
        next_hop:
          address: 10.64.100.1
